name: auto-release
on:
  push:
    branches:
      - develop
jobs:
  build:
   runs-on: ubuntu-18.04
   steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: ğŸ“¦ Install Node LTS
      uses: actions/setup-node@v3
      with:
        node-version: lts/*
    - name: âœï¸ Configuraciones para firmar commits
      run: |
          git config --local user.name "${{ secrets.GIT_USER }}"
          git config --local user.email "${{ secrets.GIT_EMAIL }}"
    - name: ğŸš› Cargando dependencias
      run: npm install
    - name: ğŸ“ Creando release
      run: npm run release
    - name: ğŸ”ƒ Preparando el push para el release
      run: |
          git fetch
          git pull
          git push
          git push origin --follow-tags
    - name: ğŸ”„ Sincronizando ramas
      run: |
          git checkout main
          git fetch
          git pull
          git push
