name: auto-release
on:
  push:
    branches:
      - develop
jobs:
  build:
   runs-on: ubuntu-18.04
   steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
        token: ${{ github.token }}
    - name: ğŸ“¦ Install Node LTS
      uses: actions/setup-node@v3
      with:
        node-version: lts/*
    - name: âœï¸ Configuraciones para firmar commits
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
    - name: ğŸš› Cargando dependencias
      run: npm install
    - name: ğŸ“ Creando release
      run: npm run release
    - name: ğŸ”ƒ Preparando el push para el release
      run: |
          git fetch
          git pull
          git branch --show-current
          git push origin ${GITHUB_REF#refs/} --force
