name: demo
on:
  push:
   branches:
    - develop
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Setup node LTS
        uses: actions/setup-node@v2
        with:
          node-version: lts/*
      - name: " ğŸ“  Actualizando git config"
        run: |
            git config --global user.email "jorge.mendez.ortega@gmail.com"
            git config --global user.name "Jorge Mendez Ortega"
      - name: " ğŸ“¦  Instalando dependencias"
        run: npm install
      - name: " ğŸ—  Generando release"
        run: "npm run release"
      - name: " ğŸ”ƒ Subiendo el release"
        run: |
            git fetch origin ${GITHUB_REF#refs/}
            git pull origin ${GITHUB_REF#refs/}
            git push origin ${GITHUB_REF#refs/} --force
