name: demo
on:
  push:
   branches:
    - develop
jobs:
  build:
    runs-on: ubuntu-18.04
    permissions:
      issues: write
      pull-requests: write
    strategy:
      matrix:
        node: ['16']
    steps:
      - uses: actions/checkout@v3
      - name: Setup node LTS
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
      - name: " ğŸ“  Actualizando git config"
        run: |
            echo ${{ secrets.GITHUB_TOKEN }}
            git config --global user.email "jorge.mendez.ortega@gmail.com"
            git config --global user.name "Jorge Mendez Ortega"
      - name: " ğŸ“¦  Instalando dependencias"
        run: npm install
      - name: " ğŸ—  Generando release"
        run: "npm run release"
      - name: " ğŸ”ƒ  Subiendo release"
        run: |
            git branch --show-current
            git fetch
            git pull
            git push --force
